# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_of_user',
            field=models.IntegerField(choices=[(0, 'bibliotecario'), (1, 'estudiante'), (2, 'visitante')], default=2),
        ),
    ]
