# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-29 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(0, 'Enviada'), (1, 'Rechazada'), (2, 'Aprobada')], default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status_notes',
            field=models.TextField(blank=True),
        ),
    ]
