# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-01 22:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_ticket_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketdescription',
            options={'verbose_name': 'Descripcion de la Ticket', 'verbose_name_plural': 'Descripciones de la ticket'},
        ),
    ]
