# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-16 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20180101_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(0, 'Enviada'), (1, 'Rechazada'), (2, 'Aprobada'), (3, 'Cancelada')], default=0),
        ),
    ]
